# Generated by Django 3.2.11 on 2022-03-01 09:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('features', models.CharField(max_length=800)),
                ('created', models.DateField(default=datetime.datetime(2022, 3, 1, 9, 12, 0, 289345))),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='TalenstsumoFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('created', models.DateField(default=datetime.datetime(2022, 3, 1, 9, 12, 0, 331756))),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
            },
        ),
        migrations.CreateModel(
            name='TalenstsumoTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('temp_name', models.CharField(max_length=800)),
                ('created', models.DateField(default=datetime.datetime(2022, 3, 1, 9, 12, 0, 332348))),
                ('temp_folder', models.ForeignKey(default=1, max_length=800, on_delete=django.db.models.deletion.CASCADE, to='InterviewApp.talenstsumofolder')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
            },
        ),
        migrations.CreateModel(
            name='RegistrationTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, default=None, max_length=800, null=True)),
                ('email', models.EmailField(max_length=800)),
                ('password', models.CharField(blank=True, default=None, max_length=800, null=True)),
                ('registered_at', models.DateField(default=datetime.datetime(2022, 3, 1, 9, 12, 0, 330819))),
                ('is_active', models.IntegerField(blank=True, default=0, null=True)),
                ('Plan', models.ForeignKey(default=1, max_length=800, on_delete=django.db.models.deletion.CASCADE, to='InterviewApp.plantable')),
                ('member_of', models.ForeignKey(blank=True, default=None, max_length=800, null=True, on_delete=django.db.models.deletion.CASCADE, to='InterviewApp.registrationtbl')),
            ],
            options={
                'verbose_name': 'Registered Users',
                'verbose_name_plural': 'Registered Users',
            },
        ),
    ]
