# Generated by Django 3.2.11 on 2022-03-01 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantable',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 3, 1, 9, 16, 43, 962620)),
        ),
        migrations.AlterField(
            model_name='registrationtbl',
            name='registered_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 1, 9, 16, 44, 5134)),
        ),
        migrations.AlterField(
            model_name='talenstsumofolder',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 3, 1, 9, 16, 44, 6123)),
        ),
        migrations.AlterField(
            model_name='talenstsumotemplates',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 3, 1, 9, 16, 44, 6723)),
        ),
    ]
