# Generated by Django 3.2.11 on 2022-03-01 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewApp', '0002_auto_20220301_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantable',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 3, 1, 9, 17, 11, 244831)),
        ),
        migrations.AlterField(
            model_name='registrationtbl',
            name='registered_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 1, 9, 17, 11, 287082)),
        ),
        migrations.AlterField(
            model_name='talenstsumofolder',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 3, 1, 9, 17, 11, 288073)),
        ),
        migrations.AlterField(
            model_name='talenstsumotemplates',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 3, 1, 9, 17, 11, 288693)),
        ),
    ]
