# Generated by Django 3.2.11 on 2022-03-09 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewApp', '0004_auto_20220308_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermapping',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 3, 9, 3, 55, 54, 612002)),
        ),
        migrations.AlterField(
            model_name='plantable',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 3, 9, 3, 55, 54, 566792)),
        ),
        migrations.AlterField(
            model_name='registrationtbl',
            name='registered_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 9, 3, 55, 54, 611072)),
        ),
        migrations.AlterField(
            model_name='talenstsumofolder',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 3, 9, 3, 55, 54, 612662)),
        ),
        migrations.AlterField(
            model_name='talenstsumotemplates',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 3, 9, 3, 55, 54, 613353)),
        ),
    ]
