# Generated by Django 3.2.11 on 2022-03-09 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewApp', '0005_auto_20220309_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermapping',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 3, 9, 3, 57, 44, 915255)),
        ),
        migrations.AlterField(
            model_name='plantable',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 3, 9, 3, 57, 44, 873389)),
        ),
        migrations.AlterField(
            model_name='registrationtbl',
            name='registered_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 9, 3, 57, 44, 914059)),
        ),
        migrations.AlterField(
            model_name='talenstsumofolder',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 3, 9, 3, 57, 44, 916266)),
        ),
        migrations.AlterField(
            model_name='talenstsumotemplates',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 3, 9, 3, 57, 44, 917027)),
        ),
    ]
